development:
  adapter: postgresql
  encoding: unicode
  database: iman_portfolio_development   # db/development.postgresql
  host: localhost
  pool: 5
  timeout: 5000
  username: deborah
  password: <%= ENV["IMAN_PORTFOLIO_PW"] %>

production:
  adapter: postgresql
  database: iman_portfolio_production
  pool: 5
  timeout: 5000
